In [28]:
link="https://docs.google.com/spreadsheets/d/e/2PACX-1vRzFOfy5dxsdPtHL5XyG9dDIegvpyD7ONvk5S9TplTIThM_WbJEATd7qxPKn7lioAK_kJ3sNQuVSNrO/pub?gid=970878581&single=true&output=csv"

In [29]:
import pandas as pd

pcm=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRzFOfy5dxsdPtHL5XyG9dDIegvpyD7ONvk5S9TplTIThM_WbJEATd7qxPKn7lioAK_kJ3sNQuVSNrO/pub?gid=970878581&single=true&output=csv")

In [30]:
pcm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  232 non-null    int64
 1   Titular                     232 non-null    object
 2   Partido                     166 non-null    object
 3   Gobierno                    232 non-null    object
 4   Inicio                      232 non-null    object
 5   Fin                         232 non-null    object
 6   Militar                     169 non-null    float64
 7   regime                      231 non-null    object
 8   Trust                       232 non-null    object
 9   Categoría                   232 non-null    object
 10  Notas / Contexto Histórico  232 non-null    object
 11  Unnamed: 11                 108 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 21.9+ KB

In [31]:
pcm.head()

,Unnamed: 0,Titular,Partido,Gobierno,Inicio,Fin,Militar,regime,Trust,Categoría,Notas / Contexto Histórico,Unnamed: 11
0,0,José María Raygada y Gallo,Militar,Ramón Castilla (II),14 de febrero de 1857,13 de mayo de 1858,1.0,constitutional,1,FIN_GOBIERNO,Primer premier de la historia peruana. Castill...,NaN
1,1,Manuel Ortiz de Zevallos y García,NaN,Ramón Castilla (II),13 de mayo de 1858,13 de julio de 1858,NaN,constitutional,1,CAMBIO_GABINETE,Castilla reorganizó su gabinete.,NaN
2,2,Miguel de San Román y Meza,Militar,Ramón Castilla (II),13 de julio de 1858,24 de octubre de 1858,1.0,constitutional,1,CAMBIO_GABINETE,San Román reemplazado en reorganización.,NaN
3,3,Miguel del Carpio y Melgar,NaN,Ramón Castilla (II),28 de octubre de 1858,9 de junio de 1860,NaN,constitutional,1,CAMBIO_GABINETE,Del Carpio reemplazado al inicio del último añ...,NaN
4,4,Juan Antonio Pezet Rodríguez,Militar,Ramón Castilla (II),9 de junio de 1860,1 de enero de 1862,1.0,constitutional,1,CAMBIO_GABINETE,Pezet fue presidente del Consejo de Ministros ...,NaN

In [32]:
pcm[pcm.Titular.str.contains(r"\[")]

,Unnamed: 0,Titular,Partido,Gobierno,Inicio,Fin,Militar,regime,Trust,Categoría,Notas / Contexto Histórico,Unnamed: 11
13,13,Juan Antonio Ugarteche Posadas[2],Militar,Pedro Diez Canseco,26 de septiembre de 1865,6 de noviembre de 1865,1.0,replaceVice,1,TRANSICION,Ugarteche fue presidente del Consejo durante e...,NaN
15,15,Mariano Ignacio Prado Ochoa[3],Militar,Mariano Ignacio Prado (I),28 de noviembre de 1865,15 de febrero de 1867,1.0,deFacto,1,REGIMEN_CAMBIA,"En su primera presidencia, Prado fue sucesivam...",NaN
18,18,Luis La Puerta[5],Militar,Mariano Ignacio Prado (I),1 de septiembre de 1867,12 de octubre de 1867,1.0,constitutional,1,TRANSICION,La Puerta encarga el poder antes de la renunci...,NaN
48,48,Antonio Arenas Merino[6],NaN,Antonio Arenas Merino,3 de diciembre de 1885,3 de junio de 1886,NaN,Provisorio,0,TRANSICION,Gobierno provisorio de Arenas hasta que Cácere...,NaN
123,123,David Samanez Ocampo[7],NaN,Junta Nacional de Gobierno,11 de marzo de 1931,8 de diciembre de 1931,NaN,constitutional,0,TRANSICION,La Junta Nacional entrega el poder a Sánchez C...,https://es.wikipedia.org/wiki/Junta_Nacional_d...

In [33]:
pcm["Titular"]=pcm.Titular.str.split("[",expand=True)[0]

In [34]:
import numpy as np
from datetime import datetime, timedelta
import locale

# 1. Configurar locale (con fallback por si estás en Windows)
try:
    locale.setlocale(locale.LC_TIME, "es_ES.UTF-8")
except locale.Error:
    locale.setlocale(locale.LC_TIME, "Spanish_Spain.1252") # Windows

# Tu función lambda (agregamos validación por si hay NaN)
str_to_date = lambda x: datetime.strptime(x, "%d de %B de %Y") if pd.notna(x) else pd.NaT

pcm[["Inicio", "Fin"]] = pcm[["Inicio", "Fin"]].apply(lambda x: x.str.strip())

In [35]:
pcm['start'] = pcm['Inicio'].apply(str_to_date)

In [36]:
pcm['end'] = pcm['Fin'].apply(str_to_date)

In [37]:
pcm.columns

Index(['Unnamed: 0', 'Titular', 'Partido', 'Gobierno', 'Inicio', 'Fin',
       'Militar', 'regime', 'Trust', 'Categoría', 'Notas / Contexto Histórico',
       'Unnamed: 11', 'start', 'end'],
      dtype='object')

In [38]:
keep=['Titular', 'Partido', 'Gobierno', 'Militar', 'regime',  'Categoría','start', 'end']

In [39]:
pcm=pcm[keep]

In [40]:
pcm

,Titular,Partido,Gobierno,Militar,regime,Categoría,start,end
0,José María Raygada y Gallo,Militar,Ramón Castilla (II),1.0,constitutional,FIN_GOBIERNO,1857-02-14,1858-05-13
1,Manuel Ortiz de Zevallos y García,NaN,Ramón Castilla (II),NaN,constitutional,CAMBIO_GABINETE,1858-05-13,1858-07-13
2,Miguel de San Román y Meza,Militar,Ramón Castilla (II),1.0,constitutional,CAMBIO_GABINETE,1858-07-13,1858-10-24
3,Miguel del Carpio y Melgar,NaN,Ramón Castilla (II),NaN,constitutional,CAMBIO_GABINETE,1858-10-28,1860-06-09
4,Juan Antonio Pezet Rodríguez,Militar,Ramón Castilla (II),1.0,constitutional,CAMBIO_GABINETE,1860-06-09,1862-01-01
...,...,...,...,...,...,...,...,...
227,Eduardo Arana Ysa,Independiente,José Jerí,0.0,Provisorio,TRANSICION,2025-10-10,2025-10-12
228,Ernesto Álvarez Miranda,Partido Popular Cristiano[13],José Jerí,0.0,Provisorio,TRANSICION,2025-10-14,2026-02-17
229,Ernesto Álvarez Miranda,Partido Popular Cristiano[13],José María Balcázar,0.0,Provisorio,CAMBIO_GABINETE,2026-02-18,2026-02-24
230,Denisse Miralles Miralles,Independiente,José María Balcázar,0.0,Provisorio,RENUNCIA_FORZADA,2026-02-24,2026-03-17
231,Luis Arroyo Sánchez,Independiente,José María Balcázar,1.0,Provisorio,TRANSICION,2026-03-17,2026-05-17

In [41]:
pcm.to_csv("premierperu.csv",index=False)