In [1]:
# coding: utf-8

import pandas as pd
from urllib.parse import quote

# Pull tables from Wikipedia
base  = "https://es.wikipedia.org/wiki/" 
path  = "Anexo:Ministros_del_Interior_del_Perú"
url   = base + quote(path)          # Per%C3%BA

# Add a User-Agent header to mimic a browser and avoid 403 Forbidden error
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
intTables = pd.read_html(url, flavor="bs4",
                      attrs={"class": "wikitable sortable"}, storage_options={"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})

In [2]:
len(intTables)

5

In [3]:
intTables[0].head()

  Titular                                             Presidente  \
   Imagen                      Nombre                 Presidente
0     NaN         Juan Manuel del Mar  Ramón Castilla (2.º gob.)
1     NaN  Jervasio Álvarez y Montaño  Ramón Castilla (2.º gob.)
2     NaN                         NaN                        NaN

                  Inicio                      Fin
                  Inicio                      Fin
0      diciembre de 1855    24 de octubre de 1856
1  24 de octubre de 1856  31 de diciembre de 1856
2                    NaN                      NaN

In [4]:
intTables[1].head()

  Titular                                              \
   Imagen                                      Nombre
0     NaN  Ignacio de Osma y Ramírez de Arellano[n 1]
1     NaN                         Juan Manuel del Mar
2     NaN                              Manuel Morales
3     NaN                  Miguel del Carpio y Melgar
4     NaN                                         NaN

                  Presidente                    Inicio  \
                  Presidente                    Inicio
0  Ramón Castilla (2.º gob.)     14 de febrero de 1857
1  Ramón Castilla (2.º gob.)        1 de abril de 1857
2  Ramón Castilla (2.º gob.)       13 de julio de 1858
3  Ramón Castilla (2.º gob.)  28 de septiembre de 1859
4                        NaN                       NaN

                        Fin
                        Fin
0        1 de abril de 1857
1       13 de julio de 1858
2  28 de septiembre de 1859
3       31 de enero de 1860
4                       NaN

In [5]:
intTables[2].head()

  Titular                               Partido  \
   Imagen                        Nombre Partido
0     NaN  José Fabio Melgar Valdivieso     NaN
1     NaN                Manuel Morales     NaN
2     NaN                Antonio Arenas     NaN
3     NaN                 Manuel Freyre     NaN
4     NaN      Cipriano Coronel Zegarra     NaN

                      Presidente                 Inicio
                      Presidente                 Inicio
0      Ramón Castilla (2.º gob.)    31 de enero de 1860
1      Ramón Castilla (2.º gob.)    29 de marzo de 1860
2            Miguel de San Román  24 de octubre de 1862
3  Pedro Díez-Canseco (interino)    10 de abril de 1863
4             Juan Antonio Pezet    5 de agosto de 1863

In [6]:
intTables[3].head()

  Titular                            Partido          Presidente  \
   Imagen                     Nombre Partido          Presidente
0     NaN              Benjamín Boza     NaN  Nicolás de Piérola
1     NaN    José María de la Puente     NaN  Nicolás de Piérola
2     NaN            Lorenzo Arrieta     NaN  Nicolás de Piérola
3     NaN  Alejandro López de Romaña     NaN  Nicolás de Piérola
4     NaN    José María de la Puente     NaN  Nicolás de Piérola

                    Inicio
                    Inicio
0  30 de noviembre de 1895
1      8 de agosto de 1896
2     19 de agosto de 1896
3  25 de noviembre de 1897
4  23 de diciembre de 1897

In [7]:
intTables[4].head()

  Titular                               Partido                  Presidente  \
   Imagen                  Ministro     Partido                  Presidente
0     NaN   Armando Artola Azcárate  General EP       Juan Velasco Alvarado
1     NaN       Pedro Richter Prada  General EP       Juan Velasco Alvarado
2     NaN      César Campos Quesada  General EP  Francisco Morales Bermúdez
3     NaN   Luis Cisneros Vizquerra  General EP  Francisco Morales Bermúdez
4     NaN  Fernando Velit Sabattini  General EP  Francisco Morales Bermúdez

                                        Periodo
                                        Periodo
0       3 de octubre de 1968-18 de mayo de 1971
1  18 de mayo de 1971 - 3 de septiembre de 1975
2  3 de septiembre de 1975-1 de febrero de 1976
3       1 de febrero de 1976-12 de mayo de 1978
4          12 de mayo de 1978-7 de mayo de 1980

# concat

In [8]:
inta=pd.concat(intTables[:2],ignore_index=True)

In [9]:
intb=pd.concat(intTables[2:4],ignore_index=True)

In [10]:
intc=intTables[4]
inta=inta[~inta.isnull().all(axis=1)]
intb=intb[~intb.isnull().all(axis=1)]
intc=intc[~intc.isnull().all(axis=1)]

In [11]:
inta.columns

MultiIndex([(   'Titular',     'Imagen'),
            (   'Titular',     'Nombre'),
            ('Presidente', 'Presidente'),
            (    'Inicio',     'Inicio'),
            (       'Fin',        'Fin')],
           )

In [12]:
intb.columns

MultiIndex([(   'Titular',     'Imagen'),
            (   'Titular',     'Nombre'),
            (   'Partido',    'Partido'),
            ('Presidente', 'Presidente'),
            (    'Inicio',     'Inicio')],
           )

In [13]:
intc.columns

MultiIndex([(   'Titular',     'Imagen'),
            (   'Titular',   'Ministro'),
            (   'Partido',    'Partido'),
            ('Presidente', 'Presidente'),
            (   'Periodo',    'Periodo')],
           )

In [14]:
inta.columns=[b for a,b in inta.columns]
intb.columns=[b for a,b in intb.columns]
intc.columns=[b for a,b in intc.columns]

In [15]:
intb["Fin"] = intb["Inicio"].shift(-1)
intb

,Imagen,Nombre,Partido,Presidente,Inicio,Fin
0,NaN,José Fabio Melgar Valdivieso,NaN,Ramón Castilla (2.º gob.),31 de enero de 1860,29 de marzo de 1860
1,NaN,Manuel Morales,NaN,Ramón Castilla (2.º gob.),29 de marzo de 1860,24 de octubre de 1862
2,NaN,Antonio Arenas,NaN,Miguel de San Román,24 de octubre de 1862,10 de abril de 1863
3,NaN,Manuel Freyre,NaN,Pedro Díez-Canseco (interino),10 de abril de 1863,5 de agosto de 1863
4,NaN,Cipriano Coronel Zegarra,NaN,Juan Antonio Pezet,5 de agosto de 1863,11 de agosto de 1864
...,...,...,...,...,...,...
156,NaN,Javier Alva Orlandini,Acción Popular,Fernando Belaúnde Terry,15 de septiembre de 1965,26 de octubre de 1966
157,NaN,Luis Alayza Escardó,Acción Popular,Fernando Belaúnde Terry,26 de octubre de 1966,9 de julio de 1967
158,NaN,Luis Ponce Arenas,Marino,Fernando Belaúnde Terry,9 de julio de 1967,2 de junio de 1968
159,NaN,Carlos Velarde Cabello,Acción Popular,Fernando Belaúnde Terry,2 de junio de 1968,2 de octubre de 1968
160,NaN,Manuel Velarde Aspíllaga,Acción Popular,Fernando Belaúnde Terry,2 de octubre de 1968,None

In [16]:
intc[["Inicio","Fin"]]=intc.Periodo.str.split("-",expand=True)

In [17]:
inta.columns, intb.columns, intc.columns

(Index(['Imagen', 'Nombre', 'Presidente', 'Inicio', 'Fin'], dtype='object'),
 Index(['Imagen', 'Nombre', 'Partido', 'Presidente', 'Inicio', 'Fin'], dtype='object'),
 Index(['Imagen', 'Ministro', 'Partido', 'Presidente', 'Periodo', 'Inicio',
        'Fin'],
       dtype='object'))

In [18]:
intc.drop(columns=["Periodo"],inplace=True)
intc.rename(columns={"Ministro":"Nombre"},inplace=True)

In [19]:
inter=pd.concat([inta, intb, intc],ignore_index=True)

In [20]:
inter.drop(columns=["Imagen"],inplace=True)

# date text cleaning

In [21]:
inter[inter["Inicio"].isnull()]

Empty DataFrame
Columns: [Nombre, Presidente, Inicio, Fin, Partido]
Index: []

In [22]:
inter[inter["Fin"].isnull()]

,Nombre,Presidente,Inicio,Fin,Partido
166,Manuel Velarde Aspíllaga,Fernando Belaúnde Terry,2 de octubre de 1968,None,Acción Popular

In [23]:
inter.loc[167,:]

Nombre        Armando Artola Azcárate
Presidente      Juan Velasco Alvarado
Inicio           3 de octubre de 1968
Fin                18 de mayo de 1971
Partido                    General EP
Name: 167, dtype: object

In [24]:
inter.loc[166,"Fin"]="3 de octubre de 1968"

In [25]:
inter[inter.Inicio.str.contains("del")]

Empty DataFrame
Columns: [Nombre, Presidente, Inicio, Fin, Partido]
Index: []

In [26]:
inter[inter.Fin.str.contains("del")]

,Nombre,Presidente,Inicio,Fin,Partido
188,César Saucedo Sánchez,Alberto Fujimori,19 de agosto de 1999,29 de julio del 2000,General EP (r)

In [27]:
inter.loc[188,"Fin"]="29 de julio de 2000"

In [28]:
inter[inter["Inicio"].str.split("de").apply(len)!=3]

,Nombre,Presidente,Inicio,Fin,Partido
0,Juan Manuel del Mar,Ramón Castilla (2.º gob.),diciembre de 1855,24 de octubre de 1856,NaN
45,Manuel Velarde Seoane,Lizardo Montero,enero de 1883,abril de 1883,Militar
46,Federico Herrera,Lizardo Montero,abril de 1883,3 de enero de 1883,NaN

In [29]:
inter.loc[0,"Inicio"]="1 de diciembre de 1855"
inter.loc[45,"Inicio"]="17 de enero de 1883"
inter.loc[46,"Inicio"]="29 de mayo de 1883"

In [30]:
inter[inter["Fin"].str.split("de").apply(len)!=3]

,Nombre,Presidente,Inicio,Fin,Partido
44,Camilo Carrillo Martínez,Lizardo Montero,4 de septiembre de 1882,enero de 1883,Marino
45,Manuel Velarde Seoane,Lizardo Montero,17 de enero de 1883,abril de 1883,Militar
241,José Zapata Morante,José María Balcázar,17 de marzo de 2026,,NaN

In [31]:
inter.loc[44,"Fin"]="10 de enero de 1883"
inter.loc[45,"Fin"]="29 de mayo de 1883"
inter.loc[46,"Fin"]="25 de octubre de 1883"

In [32]:
inter[inter.Inicio=='']

Empty DataFrame
Columns: [Nombre, Presidente, Inicio, Fin, Partido]
Index: []

In [33]:
inter[inter.Fin=='']

                  Nombre           Presidente               Inicio Fin Partido
241  José Zapata Morante  José María Balcázar  17 de marzo de 2026         NaN

In [34]:
inter.loc[241,"Fin"]=None

In [35]:
import numpy as np
from datetime import datetime, timedelta
import locale

# 1. Configurar locale (con fallback por si estás en Windows)
try:
    locale.setlocale(locale.LC_TIME, "es_ES.UTF-8")
except locale.Error:
    locale.setlocale(locale.LC_TIME, "Spanish_Spain.1252") # Windows

# Tu función lambda (agregamos validación por si hay NaN)
str_to_date = lambda x: datetime.strptime(x, "%d de %B de %Y") if pd.notna(x) else pd.NaT

inter[["Inicio", "Fin"]] = inter[["Inicio", "Fin"]].apply(lambda x: x.str.strip())

# Date format

In [36]:
# 2. Convertir a datetime
inter['fecha_start'] = inter['Inicio'].apply(str_to_date)
inter['fecha_end'] = inter['Fin'].apply(str_to_date)

In [37]:
inter[inter.fecha_start>inter.fecha_end]

,Nombre,Presidente,Inicio,Fin,Partido,fecha_start,fecha_end
34,Manuel Yrigoyen Arias (interino),Mariano Ignacio Prado (2.º gob.),19 de octubre de 1879,25 de octubre de 1878,NaN,1879-10-19,1878-10-25

In [38]:
inter.loc[34,"Inicio"]="19 de octubre de 1878"

In [39]:
inter[['fecha_start','fecha_end']]=inter[['Inicio','Fin']].map(str_to_date)

In [40]:
inter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nombre       242 non-null    object
 1   Presidente   242 non-null    object
 2   Inicio       242 non-null    object
 3   Fin          241 non-null    object
 4   Partido      124 non-null    object
 5   fecha_start  242 non-null    datetime64[ns]
 6   fecha_end    241 non-null    datetime64[ns]
dtypes: datetime64[ns](2), object(5)
memory usage: 13.4+ KB

In [41]:
inter.to_pickle("inter.pkl")